### ISSUE TITLE
TRSS Windows端无法绘图

### ISSUE THREAD

**Issue by SnowryFox** [CikeyQi/nai-plugin#3]
报错如下

0|TRSS-Yunzai  | [TRSSYz][18:12:02.014][INFO] [wxid_l7nz39h8q3cs22] 好友消息：[wxid_6strsk333jn122] #绘图
0|TRSS-Yunzai  | [TRSSYz][18:12:02.046][MARK] [跑路插件][run][wxid_6strsk333jn122] #绘图
0|TRSS-Yunzai  | [TRSSYz][18:12:02.229][MARK] [nai-绘图][txt2img][wxid_6strsk333jn122] #绘图
0|TRSS-Yunzai  | [TRSSYz][18:12:02.234][INFO] [wxid_l7nz39h8q3cs22 => wxid_6strsk333jn122] 发送好友消息：[{"type":"text","data":{"text":"当前队列还有0人，大概还需要14秒完成"}}]
0|TRSS-Yunzai  | [TRSSYz][18:12:02.236][MARK] [nai-绘图][txt2img] #绘图 处理完成 7ms
0|TRSS-Yunzai  | [TRSSYz][18:12:23.287][ERRO] 【nai-Plugin v0.0.1】 TypeError: Cannot read properties of null (reading 'data')
0|TRSS-Yunzai  |     at getPicture (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/plugins/nai-plugin/components/Core.js:37:42)
0|TRSS-Yunzai  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
0|TRSS-Yunzai  |     at async taskQueue.processNextTask (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/plugins/nai-plugin/components/Queue.js:43:27)
0|TRSS-Yunzai  | [TRSSYz][18:12:23.287][INFO] [wxid_l7nz39h8q3cs22 => wxid_6strsk333jn122] 发送好友消息：[{"type":"text","data":{"text":"出错啦，请联系开发者"}}]

**Comment by CikeyQi** [comment]
这个错误一般是response返回内容不正确引起的，请截图控制台完整报错（理应有Axios请求错误）

**Comment by CikeyQi** [comment]
已经更新抓取错误方法，建议更新后查看问题

**Comment by SnowryFox** [comment]
现在变成一段很长的axios报错

```
[20:04:41.082][MARK] [跑路插件][run］[wxid_6strsk333jn122] #绘图
[20:04:41.083][MARK] [咸鱼_统计][adduser][wxid_6strsk333jn122] #绘图
[20:04:41.262][MARK] [nai-绘图][txt2img][wxid_6strsk333jn122] #绘图
[20:04:41.273][MARK] [nai-绘图][txt2img] #绘图 处理完成 10ms
[20:04:59.934][MARK] NaN 非好友, 无法推送签到消息
[20:05:00.025][MARK] liulian-plugin —— B站动态定时推送
[20:05:02.328][ERRO] 【nai-Plugin v0.0.1】 AxiosError: connect ETIMEDOUT 173.252.88.67:443
    at Function.AxiosError.from (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/node_modules/.pnpm/axios@1.6.2/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/node_modules/.pnpm/axios@1.6.2/node_modules/axios/lib/adapters/http.js:606:25)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (D:\weixinyunzai\TRSS-Yunzai\Yunzai\node_modules\.pnpm\follow-redirects@1.15.2_debug@4.3.4\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  port: 443,
  address: '173.252.88.67',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -4039,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      authority: 'api.novelai.net',
      Origin: 'https://novelai.net',
      Referer: 'https://novelai.net',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
      Authorization: 'Bearer pst-2RBPmeoqPzPXejTo9FvjaQJwNwCpxGziqNGhwN2Hft2m9bo89svfxk3bNFKVp7p8',
      'Content-Length': '631',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    httpsAgent: null,
    responseType: 'arraybuffer',
    method: 'post',
    url: 'https://api.novelai.net/ai/generate-image',
    data: '{"input":"miku","model":"nai-diffusion-3","action":"generate","parameters":{"width":832,"height":1216,"scale":5,"sampler":"k_euler","steps":28,"n_samples":1,"ucPreset":0,"qualityToggle":true,"sm":false,"sm_dyn":false,"dynamic_thresholding":false,"controlnet_strength":1,"legacy":false,"add_original_image":false,"uncond_scale":1,"cfg_rescale":0,"noise_schedule":"native","seed":6558396147,"negative_prompt":"nsfw, lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]"}}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'https:',
      path: '/ai/generate-image',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'api.novelai.net',
      port: '',
      agent: null,
      nativeProtocols: [Object],
      pathname: '/ai/generate-image'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 631,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '631',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /ai/generate-image HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'authority: api.novelai.net\r\n' +
        'Origin: https://novelai.net\r\n' +
        'Referer: https://novelai.net\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0\r\n' +
        'Authorization: Bearer pst-2RBPmeoqPzPXejTo9FvjaQJwNwCpxGziqNGhwN2Hft2m9bo89svfxk3bNFKVp7p8\r\n' +
        'Content-Length: 631\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.novelai.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ai/generate-image',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.novelai.net',
      protocol: 'https:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'https://api.novelai.net/ai/generate-image',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ETIMEDOUT 173.252.88.67:443
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
    errno: -4039,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '173.252.88.67',
    port: 443
  }
}
```

**Comment by CikeyQi** [comment]
你没配置代理吧？
NovelAI不能直连，需要代理才能连接

**Comment by SnowryFox** [comment]
代理是开的
![mmexport1701521494416](https://github.com/CikeyQi/nai-plugin/assets/88602057/09d04f81-490e-4769-b941-f77661c6e9f1)

**Comment by SnowryFox** [comment]
config也配置了
![mmexport1701521695436](https://github.com/CikeyQi/nai-plugin/assets/88602057/3a0e81a6-f867-4689-a7ca-c9330aab9018)

**Comment by SnowryFox** [comment]
现在是axios报错402，换了多个节点依旧如此

```
[20:57:34.022][MARK] [跑路插件][run][wxid_6strsk333jn122] #绘图
[20:57:34.024][MARK] [咸鱼_统计][adduser][wxid_6strsk333jn122] #绘图
[20:57:34.208][MARK] [nai-绘图][txt2img][wxid_6strsk333jn122] #绘图
[20:57:34.214][MARK] [nai-绘图][txt2img] #绘图 处理完成 6ms
[20:57:37.254][ERRO] 【nai-Plugin v0.0.1】 AxiosError: Request failed with status code 402
    at settle (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/node_modules/.pnpm/axios@1.6.2/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///D:/weixinyunzai/TRSS-Yunzai/Yunzai/node_modules/.pnpm/axios@1.6.2/node_modules/axios/lib/adapters/http.js:585:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      authority: 'api.novelai.net',
      Origin: 'https://novelai.net',
      Referer: 'https://novelai.net',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0',
      Authorization: 'Bearer pst-2RBPmeoqPzPXejTo9FvjaQJwNwCpxGziqNGhwN2Hft2m9bo89svfxk3bNFKVp7p8',
      'Content-Length': '631',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    httpsAgent: HttpsProxyAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      options: [Object],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      proxy: [URL],
      proxyHeaders: {},
      connectOpts: [Object],
      [Symbol(kCapture)]: false,
      [Symbol(AgentBaseInternalState)]: [Object]
    },
    responseType: 'arraybuffer',
    method: 'post',
    url: 'https://api.novelai.net/ai/generate-image',
    data: '{"input":"miku","model":"nai-diffusion-3","action":"generate","parameters":{"width":832,"height":1216,"scale":5,"sampler":"k_euler","steps":28,"n_samples":1,"ucPreset":0,"qualityToggle":true,"sm":false,"sm_dyn":false,"dynamic_thresholding":false,"controlnet_strength":1,"legacy":false,"add_original_image":false,"uncond_scale":1,"cfg_rescale":0,"noise_schedule":"native","seed":3046763322,"negative_prompt":"nsfw, lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]"}}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '631',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.novelai.net',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 9,
      connecting: false,
      _hadError: false,
      _parent: [Socket],
      _host: null,
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 35546,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /ai/generate-image HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'authority: api.novelai.net\r\n' +
      'Origin: https://novelai.net\r\n' +
      'Referer: https://novelai.net\r\n' +
      'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0\r\n' +
      'Authorization: Bearer pst-2RBPmeoqPzPXejTo9FvjaQJwNwCpxGziqNGhwN2Hft2m9bo89svfxk3bNFKVp7p8\r\n' +
      'Content-Length: 631\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.novelai.net\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: HttpsProxyAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      options: [Object],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      proxy: [URL],
      proxyHeaders: {},
      connectOpts: [Object],
      [Symbol(kCapture)]: false,
      [Symbol(AgentBaseInternalState)]: [Object]
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/ai/generate-image',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 402,
      statusMessage: 'Payment Required',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://api.novelai.net/ai/generate-image',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 24,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.novelai.net',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 631,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.novelai.net/ai/generate-image',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kEndCalled)]: true,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      authority: [Array],
      origin: [Array],
      referer: [Array],
      'user-agent': [Array],
      authorization: [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 402,
    statusText: 'Payment Required',
    headers: Object [AxiosHeaders] {
      date: 'Sat, 02 Dec 2023 12:57:37 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '66',
      connection: 'close',
      'access-control-allow-credentials': 'true',
      'access-control-allow-origin': 'https://novelai.net',
      'cache-control': 'no-store',
      vary: 'Origin',
      'x-envoy-upstream-service-time': '1072',
      'cf-cache-status': 'DYNAMIC',
      server: 'cloudflare',
      'cf-ray': '82f3bc9079e29e38-SIN'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      httpsAgent: [HttpsProxyAgent],
      responseType: 'arraybuffer',
      method: 'post',
      url: 'https://api.novelai.net/ai/generate-image',
      data: '{"input":"miku","model":"nai-diffusion-3","action":"generate","parameters":{"width":832,"height":1216,"scale":5,"sampler":"k_euler","steps":28,"n_samples":1,"ucPreset":0,"qualityToggle":true,"sm":false,"sm_dyn":false,"dynamic_thresholding":false,"controlnet_strength":1,"legacy":false,"add_original_image":false,"uncond_scale":1,"cfg_rescale":0,"noise_schedule":"native","seed":3046763322,"negative_prompt":"nsfw, lowres, {bad}, error, fewer, extra, missing, worst quality, jpeg artifacts, bad quality, watermark, unfinished, displeasing, chromatic aberration, signature, extra digits, artistic error, username, scan, [abstract]"}}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '631',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /ai/generate-image HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'authority: api.novelai.net\r\n' +
        'Origin: https://novelai.net\r\n' +
        'Referer: https://novelai.net\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0\r\n' +
        'Authorization: Bearer pst-2RBPmeoqPzPXejTo9FvjaQJwNwCpxGziqNGhwN2Hft2m9bo89svfxk3bNFKVp7p8\r\n' +
        'Content-Length: 631\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.novelai.net\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [HttpsProxyAgent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/ai/generate-image',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.novelai.net',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kUniqueHeaders)]: null
    },
    data: <Buffer 7b 22 73 74 61 74 75 73 43 6f 64 65 22 3a 34 30 32 2c 22 6d 65 73 73 61 67 65 22 3a 22 4e 6f 74 20 65 6e 6f 75 67 68 20 41 6e 6c 61 73 20 28 6e 65 65 ... 16 more bytes>
  }
}
```

**Comment by CikeyQi** [comment]
请问你购买了NovelAI官方的订阅吗？

**Comment by SnowryFox** [comment]
买了
可能是开了TUN模式的缘故，好像可以了
